apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kdp-ai-agent-configuration
  namespace: kdp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: kdp-ai-agent-configuration
    creationPolicy: Owner
    template:
      data:
        .env.local: "{{ .config | toString }}"
  data:
  - secretKey: config
    remoteRef:
      key: kdp-ai-agent-configuration
