---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-certs
  namespace: guac                     # <- where the Secret lives
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway          # <- where the Gateway lives
  to:
  - group: ""
    kind: Secret
    name: guac-tls                    # optional; omit to allow all
  - group: ""
    kind: Secret
    name: guac-tls-gw
  - group: ""
    kind: Secret
    name: api-guac-tls-gw
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-certs
  namespace: codimd
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway
  to:
  - group: ""
    kind: Secret
    name: codimd-tls
  - group: ""
    kind: Secret
    name: codimd-tls-gw
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-certs
  namespace: auth
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway
  to:
  - group: ""
    kind: Secret
    name: auth-dex-tls
  - group: ""
    kind: Secret
    name: auth-dex-tls-gw
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-certs
  namespace: kdp
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: envoy-gateway
  to:
  - group: ""
    kind: Secret
    name: kdp-dashboard-tls
  - group: ""
    kind: Secret
    name: kdp-kcp-public
  - group: ""
    kind: Secret
    name: kdp-dashboard-tls-gw
  - group: ""
    kind: Secret
    name: kdp-kcp-public-gw
---
