apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  labels:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/name: flagd
data:
  config.json: |
    {
      "flags": {
        "ui-builder-enabled": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "on"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  labels:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/name: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: flagd
      app.kubernetes.io/name: flagd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: flagd
        app.kubernetes.io/name: flagd
    spec:
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:v0.12.9
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          args:
            - start
            - --uri=file:/etc/flagd/config.json
            - --port=8013
          ports:
            - containerPort: 8013
              name: flagd
            - containerPort: 8014
              name: management
          volumeMounts:
            - name: config
              mountPath: /etc/flagd
      volumes:
        - name: config
          configMap:
            name: flagd-config
---
apiVersion: v1
kind: Service
metadata:
  name: flagd
  labels:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/name: flagd
spec:
  type: ClusterIP
  ports:
    - port: 8013
      targetPort: flagd
      protocol: TCP
      name: http
    - port: 8014
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/name: flagd
