name: "Slack scheduled message testing (every 20 minutes)"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://github.com/cncf.png?size=48
          SLACK_USERNAME: cncf-slack-reminders
          SLACK_MSG_AUTHOR: cncf-automation
          SLACK_TITLE: "CNCF Automation Testing"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
          SLACK_CHANNEL: cncf-automation-scheduled-message-testing
          MSG_MINIMAL: "true"
          SLACK_MESSAGE: "testing scheduled messaging, every 20 minutes"
