name: "Slack scheduled message testing (every 20 minutes)"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://github.com/cncf.png?size=48
          SLACK_USERNAME: cncf-slack-reminders
          SLACK_MSG_AUTHOR: cncf-automation
          MSG_MINIMAL: "true"
          # add a new SLACK_WEBHOOK for each channel you want to message
          # create the webhook here:
          # https://api.slack.com/apps/A0A9VUYC3ME/incoming-webhooks
          SLACK_CHANNEL: cncf-automation-scheduled-message-testing
          # add secrets in the cncf/automation repo here:
          # https://github.com/cncf/automation/settings/secrets/actions
          # name format: `SLACK_WEBHOOK_<channel_name_in_uppercase_and_underscores>`
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
          # change the title and message as needed
          SLACK_TITLE: "CNCF Automation Testing"
          SLACK_MESSAGE: "testing scheduled messaging, every 20 minutes"
